In [1]:
import pandas as pd 
import tensorflow as tf 
from tensorflow.keras import layers

In [6]:
data=pd.read_csv("Iris.csv",index_col="Id")[:2000]
print(data.head())
data=data.sample(frac=1)
features=data.drop(["Species"],axis=1)
labels=data["Species"]
labels=pd.get_dummies(labels)
features=tf.cast(tf.constant(features),dtype=tf.float32)
labels=tf.cast(tf.constant(labels),dtype=tf.float32)
print(features.shape,labels.shape)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
(150, 4) (150, 3)


In [3]:
model=tf.keras.Sequential([
    layers.Dense(9,activation="relu"),                      
    layers.Dense(6,activation="relu"),
    layers.Dense(3),
    layers.Activation("softmax")
])

In [4]:
model.build(input_shape=(2000,4))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (2000, 9)                 45        
                                                                 
 dense_1 (Dense)             (2000, 6)                 60        
                                                                 
 dense_2 (Dense)             (2000, 3)                 21        
                                                                 
 activation (Activation)     (2000, 3)                 0         
                                                                 
Total params: 126
Trainable params: 126
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.categorical_crossentropy,
    metrics=["accuracy"]
)

In [8]:
model.fit(
    features,
    labels,
    epochs=100
)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1312 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1108 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0930 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0845 - accuracy: 0.3867
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0743 - accuracy: 0.5800
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0652 - accuracy: 0.6600
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0573 - accuracy: 0.6667
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0515 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0450 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0386 - accuracy: 0.6667
Epoch 11/100
5/5 [===========

In [10]:
predictions=(model.predict(features)>0.5).astype(int)
for i in range(50):
    print(features[i],predictions[i],labels[i])
    print(tf.math.reduce_max(labels[i]))

5/5 [==============================] - 0s 2ms/step
tf.Tensor([5.4 3.  4.5 1.5], shape=(4,), dtype=float32) [0 0 0] tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([4.4 3.2 1.3 0.2], shape=(4,), dtype=float32) [1 0 0] tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([7.7 3.  6.1 2.3], shape=(4,), dtype=float32) [0 0 1] tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([4.4 3.  1.3 0.2], shape=(4,), dtype=float32) [1 0 0] tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([6.9 3.1 5.1 2.3], shape=(4,), dtype=float32) [0 0 1] tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([5.8 2.8 5.1 2.4], shape=(4,), dtype=float32) [0 0 1] tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([5.  2.3 3.3 1. ], sh